frontend:
  replicaCount: 1
  image:
    repository: onekeys/frontend
    tag: ""
    pullPolicy: IfNotPresent
  backendUrl: "10.102.90.130"

postgres:
  replicaCount: 1
  image:
    repository: onekeys/postgres
    tag: ""
    pullPolicy: IfNotPresent
  database:
    name: perntodo
  storage:
    size: 1Gi

backend:
  replicaCount: 1
  image:
    repository: onekeys/backend
    tag: ""
    pullPolicy: IfNotPresent
  dbHost: "10.97.118.32"